export type ProjectTag = "nextjs" | "wordpress" | "html";

export type Project = {
  id: string;
  name: string;
  category: string;
  tag: ProjectTag;
  tagline: string;
  stack: string[];
  image: string;
  concept?: boolean;
};

/** `lead` = projects shown first in that tab's carousel, in this order. */
export const PROJECT_FILTERS: { tag: ProjectTag | "all"; label: string; lead?: string[] }[] = [
  { tag: "all",       label: "Tous" },
  { tag: "nextjs",    label: "React / Next.js", lead: ["dental", "kinetik", "moon", "renova", "wonder", "parfumerie"] },
  { tag: "wordpress", label: "WordPress",       lead: ["brows"] },
  { tag: "html",      label: "HTML",            lead: ["eclat", "connect", "infini", "mosa"] },
];

export const PROJECTS: Project[] = [
  {
    id: "forma",
    name: "Forma Immobilier",
    category: "Agence immo · Next.js",
    tag: "nextjs",
    tagline: "Agence immobilière avec moteur de recherche avancé, fiches biens, prise de rendez-vous et espace propriétaire sécurisé.",
    stack: ["Next.js", "Tailwind", "React"],
    image: "/portfolio/forma.webp",
  },
  {
    id: "parfumerie",
    name: "Maison Parfumerie",
    category: "E-commerce · Next.js",
    tag: "nextjs",
    tagline: "Boutique e-commerce haut de gamme : catalogue, panier, paiement Stripe et interface d’administration.",
    stack: ["Next.js", "React", "Tailwind"],
    image: "/portfolio/parfumerie.webp",
  },
  {
    id: "aivana",
    name: "Aivana SaaS",
    category: "Dashboard IA · Next.js",
    tag: "nextjs",
    tagline: "Tableau de bord SaaS avec analyses prédictives, automatisation IA et rapports personnalisés.",
    stack: ["Next.js", "Tailwind", "OpenAI"],
    image: "/portfolio/aivana.webp",
    concept: true,
  },
  {
    id: "brows",
    name: "Brows Creative",
    category: "E-commerce · WordPress",
    tag: "wordpress",
    tagline: "Boutique WooCommerce pour salon de beauté : catalogue soins, réservations en ligne et boutique intégrée.",
    stack: ["WordPress", "WooCommerce", "Elementor"],
    image: "/portfolio/brows.webp",
  },
  {
    id: "ajc",
    name: "AJC Ingénierie",
    category: "Formation · WordPress",
    tag: "wordpress",
    tagline: "Site d’un organisme de formation certifié Qualiopi : catalogue de formations, dispositifs de financement et espaces entreprise / candidat.",
    stack: ["WordPress", "Responsive", "SEO"],
    image: "/portfolio/ajc.webp",
  },
  {
    id: "papillon-dor",
    name: "Papillon d’Or",
    category: "Transport adapté · WordPress",
    tag: "wordpress",
    tagline: "Site vitrine pour un service de transport de personnes à mobilité réduite : missions, engagements et contact disponible 7j/7.",
    stack: ["WordPress", "Responsive", "SEO"],
    image: "/portfolio/papillon-dor.webp",
  },
  {
    id: "auxitrol",
    name: "Auxitrol Weston",
    category: "Industrie · WordPress",
    tag: "wordpress",
    tagline: "Site corporate d’un fabricant international de capteurs aéronautiques : catalogue produits, marchés, carrières et support.",
    stack: ["WordPress", "Responsive", "SEO"],
    image: "/portfolio/auxitrol.webp",
  },
  {
    id: "tennis-bry",
    name: "Tennis Club Bry",
    category: "Club sportif · WordPress",
    tag: "wordpress",
    tagline: "Site du Tennis Club de Bry-sur-Marne : installations, adhésions, enseignement, actualités du club et réservation de courts.",
    stack: ["WordPress", "Responsive", "SEO"],
    image: "/portfolio/tennis-bry.webp",
  },
  {
    id: "cfi",
    name: "CFI Groupe",
    category: "Intégrateur IT · WordPress",
    tag: "wordpress",
    tagline: "Site corporate d’un intégrateur de solutions numériques : éducation, retail, santé, smart office, cybersécurité et IA.",
    stack: ["WordPress", "Responsive", "SEO"],
    image: "/portfolio/cfi.webp",
  },
  {
    id: "elior",
    name: "Elior",
    category: "Restauration · WordPress",
    tag: "wordpress",
    tagline: "Site d’un leader de la restauration collective : offres, engagements responsables, recrutement et actualités.",
    stack: ["WordPress", "Responsive", "SEO"],
    image: "/portfolio/elior.webp",
  },
  {
    id: "idemia",
    name: "IDEMIA",
    category: "Tech & sécurité · WordPress",
    tag: "wordpress",
    tagline: "Site d’un groupe international de l’identité et de la sécurité numérique : solutions, entités, carrières et actualités.",
    stack: ["WordPress", "Responsive", "SEO"],
    image: "/portfolio/idemia.webp",
  },
  {
    id: "verdure",
    name: "Maison Verdure",
    category: "Site vitrine · HTML",
    tag: "html",
    tagline: "Site vitrine pour une boulangerie artisanale : menu interactif, histoire de la maison et commandes en ligne.",
    stack: ["HTML", "CSS", "JavaScript"],
    image: "/portfolio/verdure.webp",
  },
  {
    id: "luxecars",
    name: "LuxeCars",
    category: "Location · React",
    tag: "nextjs",
    tagline: "Plateforme premium de location de voitures de luxe : catalogue filtrable, réservation instantanée et paiement sécurisé.",
    stack: ["React", "Vite", "Tailwind"],
    image: "/portfolio/luxecars.webp",
  },
  {
    id: "sora",
    name: "Sora Thai",
    category: "Restaurant · HTML",
    tag: "html",
    tagline: "Site élégant pour restaurant thaïlandais : carte animée, galerie immersive et module de réservation en ligne.",
    stack: ["HTML", "CSS", "JavaScript"],
    image: "/portfolio/sora.webp",
  },
  {
    id: "eclat",
    name: "Éclat",
    category: "Institut beauté · HTML",
    tag: "html",
    tagline: "Site d’un institut du regard à Paris : prestations, conseils, boutique en ligne et réservation, dans une direction artistique éditoriale.",
    stack: ["HTML", "CSS", "JavaScript"],
    image: "/portfolio/eclat.webp",
  },
  {
    id: "ajt",
    name: "AJT Blog",
    category: "Blog · Next.js",
    tag: "nextjs",
    tagline: "Blog moderne avec système de catégories, recherche plein texte, commentaires et tableau de bord auteur.",
    stack: ["React", "Next.js", "Tailwind"],
    image: "/portfolio/ajt-blog.webp",
  },
  {
    id: "dental",
    name: "Dental Clinic",
    category: "Santé · Next.js",
    tag: "nextjs",
    tagline: "Site d’un chirurgien-dentiste implantologue : soins, solutions d’implants, diagnostic en ligne et prise de rendez-vous.",
    stack: ["Next.js", "React", "Tailwind"],
    image: "/portfolio/dental.webp",
  },
  {
    id: "kinetik",
    name: "Kinetik",
    category: "Salle de sport · Next.js",
    tag: "nextjs",
    tagline: "Site d’un training club : espaces, coachs, programmes d’entraînement et réservation de séances.",
    stack: ["Next.js", "React", "Tailwind"],
    image: "/portfolio/kinetik.webp",
  },
  {
    id: "moon",
    name: "Moon",
    category: "Beauté · React",
    tag: "nextjs",
    tagline: "Marque de maquillage : collection, rituel en trois gestes, avis clientes et réservation de séances beauté.",
    stack: ["React", "Vite", "Tailwind"],
    image: "/portfolio/moon.webp",
  },
  {
    id: "renova",
    name: "Renova",
    category: "Rénovation · Next.js",
    tag: "nextjs",
    tagline: "Entreprise de rénovation d’intérieur : méthode, avantages, réalisations et demande de devis en ligne.",
    stack: ["Next.js", "React", "Tailwind"],
    image: "/portfolio/renova.webp",
  },
  {
    id: "wonder",
    name: "Wonder Club",
    category: "Barbier · React",
    tag: "nextjs",
    tagline: "Salon de coiffure et barbier : prestations et tarifs, galerie de coupes, infos pratiques et réservation de créneau.",
    stack: ["React", "Tailwind"],
    image: "/portfolio/wonder.webp",
  },
  {
    id: "connect",
    name: "Connect",
    category: "Produit tech · HTML",
    tag: "html",
    tagline: "Page produit pour un casque audio : présentation immersive, coloris, fiche technique et ajout au panier.",
    stack: ["HTML", "CSS", "JavaScript"],
    image: "/portfolio/connect.webp",
  },
  {
    id: "infini",
    name: "Infini",
    category: "Automobile · HTML",
    tag: "html",
    tagline: "Site d’un constructeur de véhicules électriques de luxe : gamme filtrable, recharge, actualités et essais.",
    stack: ["HTML", "CSS", "JavaScript"],
    image: "/portfolio/infini.webp",
  },
  {
    id: "mosa",
    name: "Mosa",
    category: "Mobilier · HTML",
    tag: "html",
    tagline: "Atelier de canapés artisanaux : collections, savoir-faire, sur-mesure et showroom, dans une mise en page éditoriale.",
    stack: ["HTML", "CSS", "JavaScript"],
    image: "/portfolio/mosa.webp",
  },
];
